version: 2
updates:
  # master branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "master"
    labels:
      - "dependencies"
      - "javascript"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "sodium-native"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "p-queue"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "p-event"
        update-types:
          - "version-update:semver-major"

  # v3 branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "v3"
    labels:
      - "dependencies"
      - "javascript"
      - "target:v3"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "html-to-text"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "pako"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "sodium-native"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "rimraf"
        update-types: 
          - "version-update:semver-major"
      - dependency-name: "mongodb"
        update-types: 
          - "version-update:semver-major"
      - dependency-name: "p-queue"
        update-types: 
          - "version-update:semver-major"
      - dependency-name: "p-event"
        update-types: 
          - "version-update:semver-major"
      - dependency-name: "https-proxy-agent"
        update-types: 
          - "version-update:semver-major"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  # v1-lts branch
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update:"
    target-branch: "v1-lts-lol"
    labels:
      - "dependencies"
      - "javascript"
      - "target:v1"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "discord.js"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "soundcloud.ts"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "https-proxy-agent"
        update-types:
          - "version-update:semver-major"

  # documentation site (master)
  - package-ecosystem: npm
    directory: "/docs/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(docs):"
    target-branch: "master"
    labels:
      - "dependencies"
      - "javascript"
      - "scope:docs"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "@mdx-js/react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "prism-react-renderer"
        update-types:
          - "version-update:semver-major"

  # actions (master)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(action):"
    target-branch: "master"
    labels:
      - "dependencies"
      - "github_actions"

  # actions (v3)
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "Update(action):"
    target-branch: "v3"
    labels:
      - "dependencies"
      - "github_actions"
      - "target:v3"
